### ISSUE TITLE
Add UMD

### ISSUE THREAD

**Issue by weslleyaraujo** [RodyRafa/list-paginator#4]

**Comment by RodyRafa** [comment]
I will close this issue o/ @weslleyaraujo thks man!

**Comment by RodyRafa** [comment]
You can check in [this commit](https://github.com/RodyRafa/list-paginator/commit/700bfae5e058fce5173f87b7b1e15380040a9ef6)

**Comment by weslleyaraujo** [comment]
awesome \o/
